### PR TITLE
Remove MyResource as it's not used anymore

### PR DESCRIPTION
**Pull request by HypedLama**
SomeResource referenced MyResource which does not exist anymore resulting in a build error. 
SomeResource has the same capabilities as SomeCell but does not implement it, thus it shouldn't be needed anymore. 
The test now tests SomeCell instead.

### CODE REVIEW

**Comment by MarisaGoergen** [comment]
@Toxantron

**Review by 1nf0rmagician — APPROVED** [review]

**Comment by Toxantron** [comment]
> @Toxantron

On the other branches they were used to show how referencing works. I know the machine template uses differente references, but removing the classes, might complicate merging in the future.

**Comment by MarisaGoergen** [comment]
`MyResource` was deleted several commits beforehand. But there was a reference in `SomeResource`, which lead to the branch not being able to build anymore.

Furthermore `SomeResource` and `SomeCell` have the same Capabilities. The moment a user creates both in the UI, there will be a problem with the production

**Comment by Toxantron** [comment]
All understandable. I am just pointing out their purpose on the other branches and want to remind you about mergeability.

**Pull request merged**
